Avis dans loadSupport(appDir, renv = sharedEnv, globalrenv = NULL) :
  Loading R/ subdirectory for Shiny application, but this directory appears to contain an R package. Sourcing files in R/ may cause unexpected behavior.
ℹ Loading archeoViz
Avis : 'rgl.init' failed, running with 'rgl.useNULL = TRUE'.

Listening on http://127.0.0.1:35725
Avis : Error in as.vector: variable facteur mal formée
  171: as.vector
  170: as.vector.factor
  168: as.vector
  167: intersect
  165: limits
  164: self$limits
  163: get_limits
  162: self$get_limits
  161: map
  160: self$map
  159: FUN
  158: lapply
  157: map_df
  156: scale$map_df
  155: FUN
  154: lapply
  152: FUN
  151: lapply
  150: ggplotly_build
  149: gg2list
  148: ggplotly.ggplot
  146: eventReactiveValueFunc [/data/user/a/archeoviz/zPublish/shiny/tai/R/app_server.R#657]
  102: map
  101: ::
plotly
renderPlotly [/data/user/a/archeoviz/zPublish/shiny/tai/R/app_server.R#660]
  100: func
   97: shinyRenderWidget
   96: func
   83: renderFunc
   82: output$map
    1: runApp
Avis : Error in as.vector: variable facteur mal formée
  171: as.vector
  170: as.vector.factor
  168: as.vector
  167: intersect
  165: limits
  164: self$limits
  163: get_limits
  162: self$get_limits
  161: map
  160: self$map
  159: FUN
  158: lapply
  157: map_df
  156: scale$map_df
  155: FUN
  154: lapply
  152: FUN
  151: lapply
  150: ggplotly_build
  149: gg2list
  148: ggplotly.ggplot
  146: eventReactiveValueFunc [/data/user/a/archeoviz/zPublish/shiny/tai/R/app_server.R#657]
  102: map
  101: ::
plotly
renderPlotly [/data/user/a/archeoviz/zPublish/shiny/tai/R/app_server.R#660]
  100: func
   97: shinyRenderWidget
   96: func
   83: renderFunc
   82: output$map
    1: runApp
Avis : `stat_contour()`: Zero contours were generated
Avis dans min(x) : aucun argument trouvé pour min ; Inf est renvoyé
Avis dans max(x) : aucun argument pour max ; -Inf est renvoyé


Exécution arrêtée

